[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "whs-calculator"
version = "0.0.1"
authors = [
    {name = "Jérôme Roeser", email = "jerome.roeser@gmail.com"},
]
description = """
              A package to scrape golf scorecards, create a sqlite database
              and compute a golf handicap index table
              """
readme = "README.md"
requires-python = ">=3.10"
keywords = ["sqllite", "scraper"]
license = {text = "MIT"}
dynamic = ["dependencies"]

[tool.setuptools.packages.find]
where = ["golf"]
namespaces = false

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
